###################################################################

# Created by write_sdc on Sun May 10 13:34:18 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current uA
create_clock [get_ports clk]  -period 40  -waveform {0 20}
set_input_delay -clock clk  2  [get_ports reset]
set_input_delay -clock clk  2  [get_ports {memdata[7]}]
set_input_delay -clock clk  2  [get_ports {memdata[6]}]
set_input_delay -clock clk  2  [get_ports {memdata[5]}]
set_input_delay -clock clk  2  [get_ports {memdata[4]}]
set_input_delay -clock clk  2  [get_ports {memdata[3]}]
set_input_delay -clock clk  2  [get_ports {memdata[2]}]
set_input_delay -clock clk  2  [get_ports {memdata[1]}]
set_input_delay -clock clk  2  [get_ports {memdata[0]}]
set_input_delay -clock clk  2  [get_ports alusrca]
set_input_delay -clock clk  2  [get_ports memtoreg]
set_input_delay -clock clk  2  [get_ports iord]
set_input_delay -clock clk  2  [get_ports pcen]
set_input_delay -clock clk  2  [get_ports regwrite]
set_input_delay -clock clk  2  [get_ports regdst]
set_input_delay -clock clk  2  [get_ports {pcsource[1]}]
set_input_delay -clock clk  2  [get_ports {pcsource[0]}]
set_input_delay -clock clk  2  [get_ports {alusrcb[1]}]
set_input_delay -clock clk  2  [get_ports {alusrcb[0]}]
set_input_delay -clock clk  2  [get_ports {irwrite[3]}]
set_input_delay -clock clk  2  [get_ports {irwrite[2]}]
set_input_delay -clock clk  2  [get_ports {irwrite[1]}]
set_input_delay -clock clk  2  [get_ports {irwrite[0]}]
set_input_delay -clock clk  2  [get_ports {alucont[2]}]
set_input_delay -clock clk  2  [get_ports {alucont[1]}]
set_input_delay -clock clk  2  [get_ports {alucont[0]}]
set_output_delay -clock clk  2  [get_ports zero]
set_output_delay -clock clk  2  [get_ports {instr[31]}]
set_output_delay -clock clk  2  [get_ports {instr[30]}]
set_output_delay -clock clk  2  [get_ports {instr[29]}]
set_output_delay -clock clk  2  [get_ports {instr[28]}]
set_output_delay -clock clk  2  [get_ports {instr[27]}]
set_output_delay -clock clk  2  [get_ports {instr[26]}]
set_output_delay -clock clk  2  [get_ports {instr[25]}]
set_output_delay -clock clk  2  [get_ports {instr[24]}]
set_output_delay -clock clk  2  [get_ports {instr[23]}]
set_output_delay -clock clk  2  [get_ports {instr[22]}]
set_output_delay -clock clk  2  [get_ports {instr[21]}]
set_output_delay -clock clk  2  [get_ports {instr[20]}]
set_output_delay -clock clk  2  [get_ports {instr[19]}]
set_output_delay -clock clk  2  [get_ports {instr[18]}]
set_output_delay -clock clk  2  [get_ports {instr[17]}]
set_output_delay -clock clk  2  [get_ports {instr[16]}]
set_output_delay -clock clk  2  [get_ports {instr[15]}]
set_output_delay -clock clk  2  [get_ports {instr[14]}]
set_output_delay -clock clk  2  [get_ports {instr[13]}]
set_output_delay -clock clk  2  [get_ports {instr[12]}]
set_output_delay -clock clk  2  [get_ports {instr[11]}]
set_output_delay -clock clk  2  [get_ports {instr[10]}]
set_output_delay -clock clk  2  [get_ports {instr[9]}]
set_output_delay -clock clk  2  [get_ports {instr[8]}]
set_output_delay -clock clk  2  [get_ports {instr[7]}]
set_output_delay -clock clk  2  [get_ports {instr[6]}]
set_output_delay -clock clk  2  [get_ports {instr[5]}]
set_output_delay -clock clk  2  [get_ports {instr[4]}]
set_output_delay -clock clk  2  [get_ports {instr[3]}]
set_output_delay -clock clk  2  [get_ports {instr[2]}]
set_output_delay -clock clk  2  [get_ports {instr[1]}]
set_output_delay -clock clk  2  [get_ports {instr[0]}]
set_output_delay -clock clk  2  [get_ports {adr[7]}]
set_output_delay -clock clk  2  [get_ports {adr[6]}]
set_output_delay -clock clk  2  [get_ports {adr[5]}]
set_output_delay -clock clk  2  [get_ports {adr[4]}]
set_output_delay -clock clk  2  [get_ports {adr[3]}]
set_output_delay -clock clk  2  [get_ports {adr[2]}]
set_output_delay -clock clk  2  [get_ports {adr[1]}]
set_output_delay -clock clk  2  [get_ports {adr[0]}]
set_output_delay -clock clk  2  [get_ports {writedata[7]}]
set_output_delay -clock clk  2  [get_ports {writedata[6]}]
set_output_delay -clock clk  2  [get_ports {writedata[5]}]
set_output_delay -clock clk  2  [get_ports {writedata[4]}]
set_output_delay -clock clk  2  [get_ports {writedata[3]}]
set_output_delay -clock clk  2  [get_ports {writedata[2]}]
set_output_delay -clock clk  2  [get_ports {writedata[1]}]
set_output_delay -clock clk  2  [get_ports {writedata[0]}]
